"""quizzes table

Revision ID: 31206a7d64b2
Revises: 45d210c68bdd
Create Date: 2020-05-18 15:57:13.707526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31206a7d64b2'
down_revision = '45d210c68bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_pub_date'), 'quizzes', ['pub_date'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=255), nullable=True),
    sa.Column('solution', sa.String(length=255), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_index(op.f('ix_quizzes_pub_date'), table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
