"""quizMarks table

Revision ID: 43ff12813a7d
Revises: cb9a28c67afc
Create Date: 2020-05-19 12:50:07.492181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ff12813a7d'
down_revision = 'cb9a28c67afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_marks',
    sa.Column('quizMarks_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('mark', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('quizMarks_id'),
    sa.UniqueConstraint('quizMarks_id')
    )
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.BOOLEAN(), nullable=True))
    op.drop_table('quiz_marks')
    # ### end Alembic commands ###
