"""user table

Revision ID: 674466b61ea9
Revises: 31206a7d64b2
Create Date: 2020-05-19 11:28:58.198640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674466b61ea9'
down_revision = '31206a7d64b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    # ### end Alembic commands ###
