"""quizMarks and LongQuestions table

Revision ID: 8f9a9bd07015
Revises: 74977a1584c4
Create Date: 2020-05-20 15:30:11.800170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9a9bd07015'
down_revision = '74977a1584c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_marks', sa.Column('feedback', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_marks', 'feedback')
    # ### end Alembic commands ###
